# Generated by Django 5.2.15 on 2026-06-04 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('graphic_design', 'Graphic Design'), ('writing', 'Writing'), ('marketing', 'Marketing'), ('languages', 'Languages'), ('video_editing', 'Video Editing'), ('photography', 'Photography'), ('music', 'Music'), ('business', 'Business'), ('tutoring', 'Tutoring'), ('data_analysis', 'Data Analysis'), ('ui_ux_design', 'UI/UX Design'), ('social_media', 'Social Media'), ('other', 'Other')], max_length=30)),
                ('skill_type', models.CharField(choices=[('offered', 'Offered'), ('wanted', 'Wanted')], max_length=10)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['-created_at'],
            },
        ),
    ]
